#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Giveitago"
# OpenGraph / Twitter Card metadata
description = "Laptop Give Away is a place to donate a laptop to the needy."
author = "Giveitago"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Laptop Give Away is a place to donate a laptop to the needy."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "&copy; Laptop Give Away"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = true

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "#155, Bengaluru, <br>Karnataka."
phone = ["+091-123-456-78"]
email = ["contactus@laptopgiveaway"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Fill the form"
link = "https://docs.google.com/forms/d/e/1FAIpQLSfz4xE-2DDPGHBb35whbdrxfBwbc67nTzf-k3XnrBU7kXC6aA/viewform"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Fill the form"
content = "For any unused electronic asset you have, please contribute to the social cause, by donating it to the needy, there by reducing ewaste."
button = "Apply"
button_link = "https://docs.google.com/forms/d/e/1FAIpQLSfz4xE-2DDPGHBb35whbdrxfBwbc67nTzf-k3XnrBU7kXC6aA/viewform"

############################# social site ########################
[[social]]
title = "laptopgiveaway"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

#[[social]]
#title = "laptopgiveaway"
#icon = "lab la-twitter"  # https://icons8.com/line-awesome
#link = "#!"

[[social]]
title = "laptopgiveaway"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

#[[social]]
#title = "laptopgiveaway"
#icon = "lab la-pinterest" # https://icons8.com/line-awesome
#link = "#!"
